### PR TITLE
chore: don't treat `*.sig` GPG signatures as `Standard ML`

### PR DESCRIPTION
**Pull request by Young-Lord**
ref:
<https://github.com/github-linguist/linguist/issues/1298> <https://github.com/biergaizi/raspberrypi-sources/pull/1>
https://github.com/Cute-Dress/Dress/discussions/50

### CODE REVIEW

**Comment by Young-Lord** [comment]
> /fast-forward

这个没rebase到master上，可能是不行的

**Comment by CuteDress** [comment]
嗯，刚刚给这个手动rebase了一下

**Comment by Young-Lord** [comment]
上面那几条貌似权限检查出锅了，我改改

**Pull request merged**
