### PR TITLE
ci: fix: `/fast-forward` triggered by non-maintainers

### PR DESCRIPTION
**Pull request by Young-Lord**
https://github.com/actions-cool/issues-helper?tab=readme-ov-file#check-issue

### CODE REVIEW

**Comment by CuteDress** [comment]
你觉得可以合了就 @ 我

**Comment by Young-Lord** [comment]
@CuteDress 这个可以了

**Comment by CuteDress** [comment]
那我是直接用 fast-forward 合？

**Comment by Young-Lord** [comment]
都行吧

**Comment by CuteDress** [comment]
那就 /fast-forward 试试

**Comment by Young-Lord** [comment]
改了 ci，fast-forward 不了（

**Comment by CuteDress** [comment]
> 都行吧 感觉 fast-forward 平时主要是给某些 clone 到本地自己给 commit 进行了签名的人用的，像这种纯 GitHub.com 在线编辑的怎么搞都行

确实，现在仓库太大不方便 clone，我也是直接在网页上操作的

**Comment by CuteDress** [comment]
> 顺带一提，这个`/fast-forward`不一定要单独作为一条评论，只要评论里包含就行了

似乎在 review 的 approve 中带有`/fast-forward`时不会触发，如[PR#58](https://github.com/Cute-Dress/Dress/pull/58#pullrequestreview-1856349856)

**Comment by 1193725591** [comment]
Thank you！
Hope toI continue to cooperate on this project!




种自己的花，爱自己的宇宙?
***@***.***



&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Cute-Dress/Dress"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年2月7日(星期三) 中午11:11
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [Cute-Dress/Dress] ci: fix: `/fast-forward` triggered by non-maintainers (PR #54)





 
Triggered from #54 (comment) by @​CuteDress.
 
Trying to  fast forward master (d53930a) to patch-4 (18cbf54).
 
Target branch (master):
 commit d53930aca21cea1b3f87fb97c0b8aae5edc500ee (HEAD -&gt; master, origin/master, origin/HEAD) Author: CuteDress ***@***.***&gt; Date:   Wed Feb 7 11:04:34 2024 +0800     Delete Souiken/IMG_0764.png          似乎是转完没删的文件
 
Pull request (patch-4):
 commit 18cbf54710c224cfc24b69fbd97f40a054db7cfe (pull_request/patch-4) Author: LY ***@***.***&gt; Date:   Mon Jan 1 15:11:13 2024 +0800     ci: fix: `/fast-forward` triggered by non-maintainers
 
Can't fast forward master (d53930a) to patch-4 (18cbf54). master (d53930a) is not a direct ancestor of patch-4 (18cbf54). Branches appear to have diverged at ca9919a:
 * d53930aca21cea1b3f87fb97c0b8aae5edc500ee Delete Souiken/IMG_0764.png * 6f10663ca01949c930cddf1c0140056347a4ba05 upload pictures * 6843f8d8fd379b283839132853d52ed43733de4b 不要在网上乱买丝袜，很透面料质量贼差，都原图直出，很一般不好穿出去 * 392bcb526d8ef32e6affdfd36b300ff37b44e440 A.R.O.N.Aのplana COS照片 * a2e8bfd83b46e2ad1d80b14eb5ec84478b907945 feat(MingxuanGame): upload pictures * 6bfad6909c1e881069c8129d8db98e1cd50a7817 JK-uniform * 8b4a2dd840c191cf6714f26f51815db3b7d05576 ci: fix: `/fast-forward` triggered by non-maintainers | * 18cbf54710c224cfc24b69fbd97f40a054db7cfe ci: fix: `/fast-forward` triggered by non-maintainers |/   * ca9919a19b30f25e6bcf53f3574934eda62ff5a3 chore: don't treat `*.sig` GPG signatures as `Standard ML`  commit ca9919a19b30f25e6bcf53f3574934eda62ff5a3 Author: LY ***@***.***&gt; Date:   Mon Jan 1 14:34:00 2024 +0800      chore: don't treat `*.sig` GPG signatures as `Standard ML`          ref:     <https://github.com/github-linguist/linguist/issues/1298&gt;     <https://github.com/biergaizi/raspberrypi-sources/pull/1&gt;
 
Rebase locally, and then force push to patch-4.

**Pull request merged**
